### ISSUE TITLE
counter will always autorotate, regardless of settings

### ISSUE THREAD

**Issue by Penguin-Spy** [GriefMoDz/statistic-counter#10]
as the title says, the counter will rotate through the possible values even if `autoRotation` is specifically set to false.

i believe the issue is this line: https://github.com/GriefMoDz/statistic-counter/blob/95f4a9259fce76923fafb40221004ef6206bf8dd/src/components/Counter.tsx#L79
the first condition of `disabled` will always be defined (and is apparently always false), so the second expression that reads the user's settings is never evaluated (in fact, when compiled from TS into JavaScript, it's entirely removed).

this appears to be an optimization for when there's only 1 counter available; perhaps you meant to use `||` (or) instead?

**Comment by GriefMoDz** [comment]
Hi, thanks for raising an issue for this. You're correct, I had meant to use an OR operator instead of a nullish coalescing. This has now been resolved under release [v1.0.2](https://github.com/GriefMoDz/statistic-counter/releases/tag/v1.0.2). Thank you.
